export const cosmetics=[
{
    id:1,
    model:"Lipsticks",
    brand:"mac",
    qty:1,
    image:"https://i.postimg.cc/6qKBqdFS/th.jpg",
    price:2000
},
{
    id:2,
    model:"Foundation",
    brand:"Hudabeauty",
    qty:1,
    image:"https://i.postimg.cc/KvrD1x3s/th-1.jpg",
    price:4000

},
{
    id:3,
    model:"Compact",
    brand:"Fitme",
    qty:1,
    image:"https://i.postimg.cc/dVHj1Vkm/th-5.jpg",
    price:500
},
{
    id:4,
    model:"Blush",
    brand:"mac",
    qty:1,
    image:"https://i.postimg.cc/NMjR2HTN/th-3.jpg",
    price:1000
},
{
    id:5,
    model:"Eyeshadowpalette",
    brand:"Revolution",
    qty:1,
    image:"https://i.postimg.cc/QNbxny2W/th-4.jpg",
    price:3000
},
]